const testGameboardArray = [
  [
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
  ],
  [
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
  ],
  [
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
  ],
  [
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
  ],
  [
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
  ],
  [
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
  ],
  [
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
  ],
  [
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
  ],
  [
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
  ],
  [
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
    { isMarked: false, ship: false },
  ],
];

export default testGameboardArray;
