const testGameboardArray = [
  [
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
  ],
  [
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
  ],
  [
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
  ],
  [
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
  ],
  [
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
  ],
  [
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
  ],
  [
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
  ],
  [
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
  ],
  [
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
  ],
  [
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
    { isMarked: false, ship: "" },
  ],
];

export default testGameboardArray;
