const testGameboardArray = [
  [
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
  ],
  [
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
  ],
  [
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
  ],
  [
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
  ],
  [
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
  ],
  [
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
  ],
  [
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
  ],
  [
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
  ],
  [
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
  ],
  [
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
    { markStatus: false, ship: false },
  ],
];

export default testGameboardArray;
